export const TITLE_ALERT_OTP = 'OTP Tidak Dapat Diproses'
export const SUB_TITLE_ALERT_OTP = 'Kami tidak dapat mengirimkan OTP untuk sementara waktu. Silakan cek kembali nomor ponsel yang Anda gunakan atau coba beberapa saat lagi.'
export const TITLE_SEND_OTP = 'Masukan kode OTP yang dikirimkan ke nomor ponsel Anda'
export const TEXT_VALIDASI_PHONE = 'Nomor ponsel wajib terdiri dari 8-15 angka'
export const MOCK_VALID_NUMBER = '87720611865'
export const MOCK_OTP_NUMBER = '123456'
