export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
//
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS'
export const VERIFY_FAILED = 'VERIFY_FAILED'
//
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'
export const REFRESH_FAILED = 'REFRESH_FAILED'
