export const LAPORAN_SUCCESS = 'LAPORAN_SUCCESS'
export const LAPORAN_FAILED = 'LAPORAN_FAILED'

export const GET_LAPORAN_SUCCESS = 'GET_LAPORAN_SUCCESS'
export const GET_LAPORAN_FAILED = 'GET_LAPORAN_FAILED'
